############# Basic Application Settings #############
spring:
  main:
    web-application-type: servlet
    banner-mode: console
  data:
    rest:
      base-path: /
  banner:
    location: banner/banner.txt
#    image:
#      location: classpath*:static/banner/banner.jpg
#      width: 721
#      height: 961

############# jdbc setting #############
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.13:3306/odor?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/odor?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: juliuslovesrenee

############# session #############
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 900
---
############# mybatis #############
mybatis:
  type-aliases-package: com.back.odor
  mapper-locations: mybatis/**/*.xml
---
############3 Logger ###############
logging:
  pattern:
    console: "%-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: error
    org.springframework: error
    com.back.odor: trace
  file:
    name: src/main/resources/logs/log.log
---
############# Server Connection Port #############
server:
  port: 8888