############# Basic Application Settings #############
spring:
  main:
    web-application-type: servlet
    banner-mode: console
  data:
    rest:
      base-path: /
  banner:
    location: banner/banner.txt
#    image:
#      location: classpath*:static/banner/banner.jpg
#      width: 721
#      height: 961

############# session #############
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 900
---
############3 Logger ###############
logging:
  pattern:
    console: "%-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: error
    org.springframework: error
    com.spring.ibatis: debug
    com.back.odor: trace
  file:
    name: src/main/resources/logs/log.log
---
############# Server Connection Port #############
server:
  port: 8888
